{
    "1fe031e6ca563c09657c8d43dc10a68e6200b675": {
        "authored_data": "2010 Jan 02 06:13",
        "commit.message": "Added deprecation for 4.0 notices. LANG-491\n\ngit-svn-id: https://svn.apache.org/repos/asf/commons/proper/lang/trunk@895132 13f79535-47bb-0310-9956-ffa450edef68\n",
        "commit.author.name": "Henri Yandell",
        "pcid": "d7a5c761704b271a478b05c97e709260b5e68ea6",
        "changes": {
            "src/java/org/apache/commons/lang3/exception/ExceptionUtils.java": {
                "old": {
                    "('org.apache.commons.lang3.exception#ExceptionUtils', None)": [
                        93,
                        128,
                        150
                    ]
                },
                "new": {
                    "('org.apache.commons.lang3.exception#ExceptionUtils', None)": [
                        60,
                        94,
                        95,
                        96,
                        131,
                        132,
                        133,
                        155,
                        156,
                        157,
                        209
                    ]
                }
            }
        }
    },
    "d7a5c761704b271a478b05c97e709260b5e68ea6": {
        "authored_data": "2010 Jan 02 06:07",
        "commit.message": "Removed the support for exceptions with a field named 'detail'. It's been there since the beginning, but does not seem like a very important use case. LANG-491\n\ngit-svn-id: https://svn.apache.org/repos/asf/commons/proper/lang/trunk@895131 13f79535-47bb-0310-9956-ffa450edef68\n",
        "commit.author.name": "Henri Yandell",
        "pcid": "99b21a45ef9112df8a41ce5b610c9a43fae0a059",
        "changes": {
            "src/java/org/apache/commons/lang3/exception/ExceptionUtils.java": {
                "old": {
                    "('org.apache.commons.lang3.exception#ExceptionUtils', 'getCause(Throwable,String)')": [
                        170
                    ],
                    "('org.apache.commons.lang3.exception#ExceptionUtils', 'getCauseUsingMethodName(Throwable,String)')": [
                        220,
                        221,
                        222,
                        223
                    ],
                    "('org.apache.commons.lang3.exception#ExceptionUtils', None)": [
                        224,
                        225,
                        226,
                        227,
                        228,
                        229,
                        230,
                        231,
                        232
                    ],
                    "('org.apache.commons.lang3.exception#ExceptionUtils', 'getCauseUsingFieldName(Throwable,String)')": [
                        233,
                        234,
                        235,
                        236,
                        237,
                        238,
                        239,
                        240,
                        241,
                        242,
                        243,
                        244,
                        245,
                        246,
                        247,
                        248
                    ]
                },
                "new": {
                    "('org.apache.commons.lang3.exception#ExceptionUtils', 'getCause(Throwable,String)')": [
                        170
                    ]
                }
            }
        }
    },
    "99b21a45ef9112df8a41ce5b610c9a43fae0a059": {
        "authored_data": "2010 Jan 02 06:02",
        "commit.message": "Removed unnecessary private toArray method. It was only invoked from one location. LANG-491\n\ngit-svn-id: https://svn.apache.org/repos/asf/commons/proper/lang/trunk@895130 13f79535-47bb-0310-9956-ffa450edef68\n",
        "commit.author.name": "Henri Yandell",
        "pcid": "e539bde39629f48d325c7a2c42c55e44ae2a76e7",
        "changes": {
            "src/java/org/apache/commons/lang3/exception/ExceptionUtils.java": {
                "old": {
                    "('org.apache.commons.lang3.exception#ExceptionUtils', None)": [
                        87,
                        88,
                        89,
                        90,
                        93,
                        94,
                        95
                    ],
                    "('org.apache.commons.lang3.exception#ExceptionUtils', 'toArray(List)')": [
                        91,
                        92
                    ],
                    "('org.apache.commons.lang3.exception#ExceptionUtils', 'getStackFrames(String)')": [
                        673
                    ]
                },
                "new": {
                    "('org.apache.commons.lang3.exception#ExceptionUtils', 'getStackFrames(String)')": [
                        664
                    ]
                }
            }
        }
    },
    "e539bde39629f48d325c7a2c42c55e44ae2a76e7": {
        "authored_data": "2010 Jan 02 05:58",
        "commit.message": "Removed the ability to modify the static store of cause method names. If that feature is wanted, it's easy for the user to pass in their own list, or use the newly added getDefaultCauseMethodNames and modify that before calling. This removes the need for synchronization code. LANG-491\n\ngit-svn-id: https://svn.apache.org/repos/asf/commons/proper/lang/trunk@895129 13f79535-47bb-0310-9956-ffa450edef68\n",
        "commit.author.name": "Henri Yandell",
        "pcid": "e87ee0a705031b111da6a99c174b6f3f1c13869f",
        "changes": {
            "src/java/org/apache/commons/lang3/exception/ExceptionUtils.java": {
                "old": {
                    "(None, None)": [
                        47
                    ],
                    "('org.apache.commons.lang3.exception#ExceptionUtils', None)": [
                        58,
                        59,
                        60,
                        64,
                        65,
                        92,
                        93,
                        94,
                        95,
                        96,
                        97,
                        98,
                        105,
                        106,
                        107,
                        108,
                        109,
                        110,
                        111,
                        112,
                        113,
                        114,
                        115,
                        116,
                        117,
                        124,
                        125,
                        126,
                        127,
                        128,
                        129,
                        139,
                        140,
                        141,
                        142,
                        146,
                        147,
                        148,
                        149,
                        150,
                        151,
                        152,
                        153,
                        154,
                        155,
                        156,
                        157,
                        161,
                        198
                    ],
                    "('org.apache.commons.lang3.exception#ExceptionUtils', 'addCauseMethodName(String)')": [
                        99,
                        100,
                        101,
                        102,
                        103,
                        104
                    ],
                    "('org.apache.commons.lang3.exception#ExceptionUtils', 'removeCauseMethodName(String)')": [
                        118,
                        119,
                        120,
                        121,
                        122,
                        123
                    ],
                    "('org.apache.commons.lang3.exception#ExceptionUtils', 'getCauseMethodNameList')": [
                        143,
                        144,
                        145
                    ],
                    "('org.apache.commons.lang3.exception#ExceptionUtils', 'isCauseMethodName(String)')": [
                        158,
                        159,
                        160
                    ],
                    "('org.apache.commons.lang3.exception#ExceptionUtils', 'getCause(Throwable)')": [
                        196,
                        197
                    ],
                    "('org.apache.commons.lang3.exception#ExceptionUtils', 'getCause(Throwable,String)')": [
                        225,
                        226,
                        227
                    ]
                },
                "new": {
                    "('org.apache.commons.lang3.exception#ExceptionUtils', None)": [
                        60,
                        96,
                        97,
                        98,
                        99,
                        100,
                        101,
                        102
                    ],
                    "('org.apache.commons.lang3.exception#ExceptionUtils', 'getDefaultCauseMethodNames')": [
                        103,
                        104
                    ],
                    "('org.apache.commons.lang3.exception#ExceptionUtils', 'getCause(Throwable)')": [
                        139
                    ],
                    "('org.apache.commons.lang3.exception#ExceptionUtils', 'getCause(Throwable,String)')": [
                        166
                    ]
                }
            },
            "src/test/org/apache/commons/lang3/exception/ExceptionUtilsTest.java": {
                "old": {
                    "('org.apache.commons.lang3.exception#ExceptionUtilsTest', None)": [
                        126,
                        133,
                        134,
                        147,
                        148,
                        149
                    ],
                    "('org.apache.commons.lang3.exception#ExceptionUtilsTest', 'testCauseMethodNameOps')": [
                        127,
                        128,
                        129,
                        130,
                        131,
                        132
                    ],
                    "('org.apache.commons.lang3.exception#ExceptionUtilsTest', 'testCauseMethodNameOps(String)')": [
                        135,
                        136,
                        137,
                        138,
                        139,
                        140,
                        141,
                        142,
                        143,
                        144,
                        145,
                        146
                    ]
                }
            }
        }
    }
}